---
title: "Headline inflation & key categories"
subtitle: ""
format: 
  revealjs:
    theme: default
    width: 1600
    height: 900
---

```{r setup}
#| include: false
library(ggplot2)
library(dplyr)
library(patchwork)


source("C:\\Users\\aelde\\OneDrive\\Documents\\GitHub\\Reports\\CPI\\CPI workings.R")



```

##  {background-color="white"}

```{r dashboard}
#| echo: false
#| warning: false
#| fig-width: 16
#| fig-height: 9

# Generate data for all 6 plots


# Combine all plots
layout <- "
ABC
DEF
"

combined <- P1 + P2 + P3 + P4 + P5 + P6 + 
  plot_layout(design = layout) +
  plot_annotation(
    title = "Headline inflation & key categories",
    theme = theme(
      plot.title = element_text(size = 20, face = "bold", hjust = 0),
      plot.subtitle = element_text(size = 14, hjust = 0)
    )
  )

combined
```

##  {background-color="white"}

```{r dashboard2}
#| echo: false
#| warning: false
#| fig-width: 16
#| fig-height: 9

# Generate data for all 6 plots


# Combine all plots
layout <- "
ABC
DEF
"

combined <- P2.1 + P2.2 + P2.3 + P2.4 + P2.5 + P2.6 + 
  plot_layout(design = layout) +
  plot_annotation(
    title = "Inlfation measures",
    theme = theme(
      plot.title = element_text(size = 20, face = "bold", hjust = 0),
      plot.subtitle = element_text(size = 14, hjust = 0)
    )
  )

combined
```


::: notes
Sources: ABS | Australian Consumer Price Index Update – Q3 2025
:::

------------------------------------------------------------------------
